var winnie = {character : "Winnie the Pooh"}
winnie.north = chrisR;
winnie.south = tigger;
winnie.west = piglet;
winnie.east = bees;
var chrisR = {character : "Christopher Robin"}
chrisR.north = kanga;
chrisR.south = winnie;
chrisR.west = owl;
chrisR.east = rabbit;
var rabbit = {character : "Rabbit"}
rabbit.south = bees;
rabbit.west = chrisR;
rabbit.east = gopher;
var tigger = {character : "Tigger"}
tigger.north = winnie;
var piglet = {character : "Piglet"}
piglet.north = owl;
piglet.east = winnie;
var owl = {character : "Owl"}
owl.east = chrisR;
owl.south = piglet;
var bees = {character : "Bees"}
bees.north = rabbit;
bees.west = winnie;
var gopher = {character : "Gopher"}
gopher.west = rabbit;
var kanga = {character : "Kanga"}
kanga.north = eeyore;
kanga.south = chrisR;
var eeyore = {character : "Eeyore"}
eeyore.south = kanga;
eeyore.east = heffalumps;
var heffalumps = {character : "Heffalumps"}
heffalumps.west = eeyore;